# Generated by Django 3.1.1 on 2020-09-23 03:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Caso_Clinico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doenca_classificada', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_doenca', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fase', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=300, null=True)),
                ('data_criacao', models.DateTimeField(default=datetime.datetime.now)),
                ('dificuldade', models.IntegerField(blank=True, choices=[(1, 'Muito facil'), (2, 'Facil'), (3, 'Normal'), (4, 'Dificil'), (5, 'Muito Dificil')], default=1, help_text='Dificuldade da pergunta')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctrainingapp.area')),
                ('responsavel_fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sintoma', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Versao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('informacao', models.CharField(max_length=600)),
                ('atualizacao_critica', models.BooleanField(default=False)),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao_Alterar_Caso_Clinico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doenca_classificada', models.BooleanField(default=True)),
                ('tipo_alteracao', models.PositiveIntegerField()),
                ('acao', models.PositiveIntegerField(default=2)),
                ('data_solicitacao', models.DateTimeField(default=datetime.datetime.now)),
                ('nome_novo_sintoma_modificado', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_nova_doenca_modificada', models.CharField(blank=True, max_length=100, null=True)),
                ('caso_clinico_a_modificar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctrainingapp.caso_clinico')),
                ('nome_doenca_a_modificar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nome_doenca_a_modificar', to='doctrainingapp.doenca')),
                ('nome_sintoma_a_modificar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nome_sintoma_a_modificar', to='doctrainingapp.sintoma')),
                ('nova_doenca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctrainingapp.doenca')),
                ('novos_sintomas', models.ManyToManyField(to='doctrainingapp.Sintoma')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sala', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
                ('data_criacao', models.DateTimeField(default=datetime.datetime.now)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctrainingapp.area')),
                ('responsavel_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerguntaFase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField(max_length=1200)),
                ('opcao_correta', models.CharField(max_length=600)),
                ('opcao_incorreta_1', models.CharField(max_length=600)),
                ('opcao_incorreta_2', models.CharField(max_length=600)),
                ('opcao_incorreta_3', models.CharField(max_length=600)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctrainingapp.fase')),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificuldade', models.IntegerField(blank=True, choices=[(1, 'Muito facil'), (2, 'Facil'), (3, 'Normal'), (4, 'Dificil'), (5, 'Muito Dificil')], default=1, help_text='Dificuldade da pergunta')),
                ('pergunta', models.TextField(max_length=1200)),
                ('opcao_correta', models.CharField(max_length=600)),
                ('opcao_incorreta_1', models.CharField(max_length=600)),
                ('opcao_incorreta_2', models.CharField(max_length=600)),
                ('opcao_incorreta_3', models.CharField(max_length=600)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctrainingapp.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(blank=True, max_length=100, null=True)),
                ('instituicao', models.CharField(max_length=100, null=True)),
                ('idade', models.PositiveIntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField()),
                ('doenca', models.CharField(max_length=100)),
                ('sintomas', models.TextField(blank=True)),
                ('nova_doenca', models.CharField(max_length=100)),
                ('novos_sintomas', models.TextField()),
                ('doenca_classificada', models.BooleanField(default=False)),
                ('tipo_alteracao', models.PositiveIntegerField()),
                ('aux_tipo_alteracao', models.CharField(max_length=100)),
                ('acao', models.PositiveIntegerField()),
                ('data_alteracao', models.DateTimeField(default=datetime.datetime.now)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliador', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('conteudo', models.TextField(max_length=1000)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('referencia', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='conteudo')),
                ('data_criacao', models.DateTimeField(default=datetime.datetime.now)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctrainingapp.area')),
            ],
        ),
        migrations.AddField(
            model_name='caso_clinico',
            name='doenca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='doctrainingapp.doenca'),
        ),
        migrations.AddField(
            model_name='caso_clinico',
            name='falsa_doenca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='falsa_doenca', to='doctrainingapp.doenca'),
        ),
        migrations.AddField(
            model_name='caso_clinico',
            name='sintomas',
            field=models.ManyToManyField(to='doctrainingapp.Sintoma'),
        ),
    ]
