# Generated by Django 2.2.5 on 2019-09-27 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao_Alterar_Caso_Clinico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doenca_classificada', models.BooleanField(default=True)),
                ('tipo_alteracao', models.PositiveIntegerField()),
                ('acao', models.PositiveIntegerField(default=10)),
                ('caso_clinico_a_modificar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='doctrainingapp.Caso_Clinico')),
                ('nova_doenca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='doctrainingapp.Doenca')),
                ('novos_sintomas', models.ManyToManyField(to='doctrainingapp.Sintoma')),
            ],
        ),
    ]
