# Generated by Django 2.2.5 on 2019-09-28 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0002_solicitacao_alterar_caso_clinico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao_alterar_caso_clinico',
            name='acao',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.CreateModel(
            name='Solicitacao_Alterar_Sintoma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nova_sintoma', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('tipo_alteracao', models.PositiveIntegerField()),
                ('acao', models.PositiveIntegerField(default=2)),
                ('sintoma_a_modificar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='doctrainingapp.Sintoma')),
            ],
        ),
    ]
