# Generated by Django 3.1.1 on 2020-09-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0002_remove_fase_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaFase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
    ]
