# Generated by Django 2.2.5 on 2019-09-28 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0003_auto_20190928_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao_alterar_sintoma',
            name='doenca_a_modificar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='doctrainingapp.Doenca'),
        ),
        migrations.AddField(
            model_name='solicitacao_alterar_sintoma',
            name='nova_doenca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacao_alterar_sintoma',
            name='nova_sintoma',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
