# Generated by Django 3.0.8 on 2020-09-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0004_fase_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='imagem1',
            field=models.ImageField(blank=True, null=True, upload_to='pergunta_sala'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='imagem2',
            field=models.ImageField(blank=True, null=True, upload_to='pergunta_sala'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='imagem3',
            field=models.ImageField(blank=True, null=True, upload_to='pergunta_sala'),
        ),
        migrations.AddField(
            model_name='perguntafase',
            name='imagem1',
            field=models.ImageField(blank=True, null=True, upload_to='pergunta_fase'),
        ),
        migrations.AddField(
            model_name='perguntafase',
            name='imagem2',
            field=models.ImageField(blank=True, null=True, upload_to='pergunta_fase'),
        ),
        migrations.AddField(
            model_name='perguntafase',
            name='imagem3',
            field=models.ImageField(blank=True, null=True, upload_to='pergunta_fase'),
        ),
    ]
