# Generated by Django 2.2.5 on 2019-09-28 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0004_auto_20190928_1446'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solicitacao_Alterar_Sintoma',
            new_name='Solicitacao_Alterar_Sintoma_Ou_Doenca',
        ),
    ]
