# Generated by Django 2.2.5 on 2019-10-11 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0005_auto_20190928_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao_alterar_caso_clinico',
            name='data_solicitacao',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
