# Generated by Django 3.0.8 on 2020-10-07 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0005_auto_20200929_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conteudo',
            name='area',
        ),
        migrations.AddField(
            model_name='conteudo',
            name='sala',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='doctrainingapp.Sala'),
            preserve_default=False,
        ),
    ]
