# Generated by Django 3.0.8 on 2020-10-07 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0006_auto_20201007_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='doctrainingapp.Area'),
            preserve_default=False,
        ),
    ]
