# Generated by Django 2.2.5 on 2019-10-14 21:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0006_solicitacao_alterar_caso_clinico_data_solicitacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogDados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField()),
                ('solicitante', models.CharField(max_length=100)),
                ('antiga_doenca', models.CharField(max_length=100)),
                ('antigos_sintomas', models.TextField(blank=True)),
                ('nova_doenca', models.CharField(max_length=100)),
                ('novos_sintomas', models.TextField()),
                ('doenca_classificada', models.BooleanField(default=False)),
                ('tipo_alteracao', models.PositiveIntegerField()),
                ('acao', models.PositiveIntegerField()),
                ('data_alteracao', models.DateTimeField(default=datetime.datetime.now)),
                ('avaliado_por', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='solicitacao_alterar_caso_clinico',
            name='caso_clinico_a_modificar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctrainingapp.Caso_Clinico'),
        ),
        migrations.AlterField(
            model_name='solicitacao_alterar_caso_clinico',
            name='nova_doenca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctrainingapp.Doenca'),
        ),
    ]
