# Generated by Django 2.2.5 on 2019-10-14 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0007_auto_20191014_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logdados',
            old_name='antiga_doenca',
            new_name='doenca',
        ),
        migrations.RenameField(
            model_name='logdados',
            old_name='antigos_sintomas',
            new_name='sintomas',
        ),
    ]
