# Generated by Django 2.2.5 on 2019-10-15 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0008_auto_20191014_1857'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogDados',
            new_name='Log',
        ),
    ]
