# Generated by Django 3.0.8 on 2020-10-08 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0008_auto_20201007_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='area',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='doctrainingapp.Area'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='conteudo',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='descricao',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='referencia',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
