# Generated by Django 2.2.5 on 2019-11-04 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctrainingapp', '0009_auto_20191015_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sala', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
                ('responsavel_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('opcao_correta', models.CharField(max_length=100)),
                ('opcao_incorreta_1', models.CharField(max_length=100)),
                ('opcao_incorreta_2', models.CharField(max_length=100)),
                ('opcao_incorreta_3', models.CharField(max_length=100)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctrainingapp.Sala')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(blank=True, max_length=100, null=True)),
                ('apelido', models.CharField(blank=True, max_length=100, null=True)),
                ('instituicao', models.CharField(blank=True, max_length=100, null=True)),
                ('idade', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
