# Generated by Django 3.0.8 on 2020-10-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0009_auto_20201007_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='fase',
            name='imagem1',
            field=models.ImageField(blank=True, null=True, upload_to='pergunta_fase'),
        ),
        migrations.AddField(
            model_name='fase',
            name='imagem2',
            field=models.ImageField(blank=True, null=True, upload_to='pergunta_fase'),
        ),
        migrations.AddField(
            model_name='fase',
            name='imagem3',
            field=models.ImageField(blank=True, null=True, upload_to='pergunta_fase'),
        ),
    ]
