# Generated by Django 2.2.5 on 2019-11-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0010_perfil_pergunta_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='idade',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
