# Generated by Django 3.0.8 on 2020-10-17 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0010_auto_20201017_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perguntafase',
            name='imagem1',
        ),
        migrations.RemoveField(
            model_name='perguntafase',
            name='imagem2',
        ),
        migrations.RemoveField(
            model_name='perguntafase',
            name='imagem3',
        ),
    ]
