# Generated by Django 2.2.5 on 2019-11-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0011_auto_20191104_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='apelido',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='instituicao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nome_completo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
