# Generated by Django 3.0.8 on 2020-11-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0011_auto_20201017_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conteudo',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='fase',
            name='descricao',
            field=models.TextField(blank=True, max_length=1000000000000000000000, null=True, verbose_name='Descrição do Problema'),
        ),
        migrations.AlterField(
            model_name='fase',
            name='nome_fase',
            field=models.CharField(max_length=50, unique=True, verbose_name='Subárea'),
        ),
    ]
