# Generated by Django 3.2.3 on 2021-05-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0012_auto_20201125_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='nome',
            field=models.CharField(help_text='Nome da área. ex.: COVID-19', max_length=50),
        ),
        migrations.AlterField(
            model_name='areafase',
            name='nome',
            field=models.CharField(help_text='Nome da área. ex.: COVID-19', max_length=50),
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='conteudo',
            field=models.TextField(blank=True, help_text='*Texto sobre o assunto.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='link',
            field=models.CharField(blank=True, help_text='*link do artigo, documentario, materia e etc ...', max_length=300),
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='titulo',
            field=models.CharField(help_text='*Título para facilitar localização na lista. ', max_length=100),
        ),
        migrations.AlterField(
            model_name='fase',
            name='descricao',
            field=models.TextField(blank=True, help_text='*Informações sobre o paciente', max_length=1000000000000000000000, null=True, verbose_name='Descrição do Problema'),
        ),
        migrations.AlterField(
            model_name='fase',
            name='dificuldade',
            field=models.IntegerField(blank=True, choices=[(1, 'Muito facil'), (2, 'Facil'), (3, 'Normal'), (4, 'Dificil'), (5, 'Muito Dificil')], default=1, help_text='Dificuldade da fase'),
        ),
        migrations.AlterField(
            model_name='fase',
            name='nome_fase',
            field=models.CharField(help_text='*Título para facilitar localização na lista. ', max_length=50, unique=True, verbose_name='Subárea'),
        ),
    ]
