# Generated by Django 2.2.5 on 2019-11-04 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0012_auto_20191104_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
