# Generated by Django 2.2.5 on 2019-11-05 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctrainingapp', '0013_sala_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao_alterar_caso_clinico',
            name='solicitante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacao_alterar_sintoma_ou_doenca',
            name='solicitante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
