# Generated by Django 2.2.5 on 2019-11-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0014_auto_20191105_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='id_user',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
