# Generated by Django 2.2.5 on 2019-11-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0015_log_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='opcao_correta',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='opcao_incorreta_1',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='opcao_incorreta_2',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='opcao_incorreta_3',
            field=models.CharField(max_length=1000),
        ),
    ]
