# Generated by Django 2.2.5 on 2019-11-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0017_auto_20191107_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='pergunta',
            field=models.TextField(max_length=1200),
        ),
    ]
