# Generated by Django 2.2.5 on 2019-12-09 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0019_auto_20191107_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='avaliado_por',
        ),
        migrations.RemoveField(
            model_name='log',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='log',
            name='solicitante',
        ),
    ]
