# Generated by Django 2.2.5 on 2019-12-09 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctrainingapp', '0020_auto_20191209_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='avaliador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='avaliador', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='solicitante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='solicitante', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
