# Generated by Django 2.2.5 on 2019-12-09 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0021_auto_20191209_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='avaliador',
        ),
        migrations.RemoveField(
            model_name='log',
            name='solicitante',
        ),
    ]
