# Generated by Django 2.2.5 on 2019-12-10 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0023_auto_20191209_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitacao_alterar_sintoma_ou_doenca',
            old_name='nova_sintoma',
            new_name='novo_sintoma',
        ),
    ]
