# Generated by Django 2.2.5 on 2019-12-11 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0024_auto_20191210_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao_alterar_caso_clinico',
            name='nome_doenca_a_modificar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nome_doenca_a_modificar', to='doctrainingapp.Doenca'),
        ),
        migrations.AddField(
            model_name='solicitacao_alterar_caso_clinico',
            name='nome_nova_doenca_modificada',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitacao_alterar_caso_clinico',
            name='nome_novo_sintoma_modificado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitacao_alterar_caso_clinico',
            name='nome_sintoma_a_modificar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nome_sintoma_a_modificar', to='doctrainingapp.Sintoma'),
        ),
    ]
