# Generated by Django 2.2.5 on 2019-12-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0025_auto_20191210_2146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Solicitacao_Alterar_Sintoma_Ou_Doenca',
        ),
    ]
