# Generated by Django 2.2.5 on 2020-01-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0026_delete_solicitacao_alterar_sintoma_ou_doenca'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='aux_tipo_alteracao',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
