# Generated by Django 2.2.5 on 2020-01-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0027_log_aux_tipo_alteracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='aux_tipo_alteracao',
            field=models.CharField(max_length=100),
        ),
    ]
