# Generated by Django 2.2.5 on 2020-01-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0028_auto_20200115_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='aux_tipo_alteracao',
            field=models.CharField(default='', max_length=100),
        ),
    ]
