# Generated by Django 3.0.8 on 2020-07-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0029_auto_20200115_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Versao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.CharField(max_length=5)),
                ('informacao', models.CharField(max_length=600)),
                ('nova_versao', models.BooleanField(default=False)),
                ('atualizacao_critica', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='log',
            name='aux_tipo_alteracao',
            field=models.CharField(max_length=100),
        ),
    ]
