# Generated by Django 3.0.8 on 2020-07-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0030_auto_20200720_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versao',
            name='versao',
            field=models.IntegerField(max_length=5),
        ),
    ]
