# Generated by Django 3.0.8 on 2020-07-29 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0031_auto_20200729_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='versao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='versao',
            name='versao',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
