# Generated by Django 3.0.8 on 2020-07-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0032_auto_20200729_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versao',
            name='versao',
            field=models.IntegerField(),
        ),
    ]
