# Generated by Django 3.0.8 on 2020-07-31 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0034_auto_20200729_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versao',
            name='nova_versao',
        ),
    ]
