# Generated by Django 3.0.8 on 2020-08-06 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0035_remove_versao_nova_versao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='sala',
            name='area',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='doctrainingapp.Area'),
            preserve_default=False,
        ),
    ]
