# Generated by Django 3.0.8 on 2020-08-06 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0036_auto_20200806_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='area',
        ),
    ]
