# Generated by Django 3.0.8 on 2020-08-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0036_area_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='salas',
        ),
        migrations.AddField(
            model_name='area',
            name='salas',
            field=models.ManyToManyField(blank=True, null=True, to='doctrainingapp.Sala'),
        ),
    ]
