# Generated by Django 3.0.8 on 2020-08-06 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0037_remove_sala_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='area',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='doctrainingapp.Area'),
            preserve_default=False,
        ),
    ]
