# Generated by Django 3.0.8 on 2020-08-10 16:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0038_sala_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('conteudo', models.TextField(max_length=1000)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('referencia', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, upload_to='conteudo')),
                ('data_criacao', models.DateTimeField(default=datetime.datetime.now)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctrainingapp.Area')),
            ],
        ),
    ]
