# Generated by Django 3.0.8 on 2020-08-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0038_auto_20200805_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='area',
        ),
        migrations.AddField(
            model_name='area',
            name='salas',
            field=models.ManyToManyField(blank=True, null=True, to='doctrainingapp.Sala'),
        ),
    ]
