# Generated by Django 3.0.8 on 2020-08-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0039_conteudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='dificuldade',
            field=models.IntegerField(blank=True, choices=[(1, 'Muito facil'), (2, 'Facil'), (3, 'Normal'), (4, 'Dificil'), (5, 'Muito Dificil')], default=1, help_text='Dificuldade da pergunta'),
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='imagem',
            field=models.ImageField(upload_to='conteudo'),
        ),
    ]
