# Generated by Django 3.0.8 on 2020-08-06 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0039_auto_20200805_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='area',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='doctrainingapp.Area'),
            preserve_default=False,
        ),
    ]
