# Generated by Django 3.0.8 on 2020-08-06 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0040_pergunta_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='salas',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='area',
        ),
        migrations.AddField(
            model_name='sala',
            name='area',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='doctrainingapp.Area'),
            preserve_default=False,
        ),
    ]
