# Generated by Django 3.0.8 on 2020-08-25 19:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctrainingapp', '0040_auto_20200818_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fase', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
                ('data_criacao', models.DateTimeField(default=datetime.datetime.now)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctrainingapp.Caso_Clinico')),
                ('responsavel_fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerguntaFase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificuldade', models.IntegerField(blank=True, choices=[(1, 'Muito facil'), (2, 'Facil'), (3, 'Normal'), (4, 'Dificil'), (5, 'Muito Dificil')], default=1, help_text='Dificuldade da pergunta')),
                ('pergunta', models.TextField(max_length=1200)),
                ('opcao_correta', models.CharField(max_length=600)),
                ('opcao_incorreta_1', models.CharField(max_length=600)),
                ('opcao_incorreta_2', models.CharField(max_length=600)),
                ('opcao_incorreta_3', models.CharField(max_length=600)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctrainingapp.Fase')),
            ],
        ),
    ]
