# Generated by Django 3.0.8 on 2020-08-25 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0041_fase_perguntafase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fase',
            old_name='area',
            new_name='caso_clinico',
        ),
    ]
