# Generated by Django 3.0.8 on 2020-08-25 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0042_auto_20200825_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perguntafase',
            old_name='sala',
            new_name='fase',
        ),
    ]
