# Generated by Django 3.0.8 on 2020-08-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0043_auto_20200825_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perguntafase',
            name='dificuldade',
        ),
        migrations.AddField(
            model_name='fase',
            name='dificuldade',
            field=models.IntegerField(blank=True, choices=[(1, 'Muito facil'), (2, 'Facil'), (3, 'Normal'), (4, 'Dificil'), (5, 'Muito Dificil')], default=1, help_text='Dificuldade da pergunta'),
        ),
    ]
