# Generated by Django 3.0.8 on 2020-09-01 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0044_auto_20200825_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='fase',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='doctrainingapp.Area'),
            preserve_default=False,
        ),
    ]
