# Generated by Django 3.0.8 on 2020-09-21 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0046_auto_20200915_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fase',
            name='caso_clinico',
        ),
    ]
