# Generated by Django 3.0.8 on 2020-09-22 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0047_remove_fase_caso_clinico'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso_clinico',
            name='falsa_doenca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='falsa_doenca', to='doctrainingapp.Doenca'),
        ),
    ]
