# Generated by Django 3.1.1 on 2020-09-22 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctrainingapp', '0048_caso_clinico_falsa_doenca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='avaliador',
        ),
        migrations.RemoveField(
            model_name='log',
            name='solicitante',
        ),
        migrations.RemoveField(
            model_name='solicitacao_alterar_caso_clinico',
            name='caso_clinico_a_modificar',
        ),
        migrations.RemoveField(
            model_name='solicitacao_alterar_caso_clinico',
            name='nome_doenca_a_modificar',
        ),
        migrations.RemoveField(
            model_name='solicitacao_alterar_caso_clinico',
            name='nome_sintoma_a_modificar',
        ),
        migrations.RemoveField(
            model_name='solicitacao_alterar_caso_clinico',
            name='nova_doenca',
        ),
        migrations.RemoveField(
            model_name='solicitacao_alterar_caso_clinico',
            name='novos_sintomas',
        ),
        migrations.RemoveField(
            model_name='solicitacao_alterar_caso_clinico',
            name='solicitante',
        ),
        migrations.DeleteModel(
            name='Caso_Clinico',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='Solicitacao_Alterar_Caso_Clinico',
        ),
    ]
